name: dilivary
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0  
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.2.0
  meta: any  # Add meta package here with the version required by leak_tracker_testing
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  leak_tracker: ^10.0.0
  leak_tracker_flutter_testing: ^2.0.1
  leak_tracker_testing: any
  material_color_utilities: ^0.8.0
  test_api: ^0.6.1
  vm_service: ^13.0.0

dependency_overrides:
  meta: ^1.11.0  # Override the version of meta required by flutter_test to match leak_tracker_testing

flutter:
  uses-material-design: true
  assets:
    - assets/Vector.jpg
    - assets/Saly-1.png
    - assets/Avatar.jpg
    - assets/login.svg
    - assets/signup.svg

